name: Test Composite Action
on: [push]

jobs:
  test-echo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Echo Composite Action
        uses: ./.github/actions/echo-action
        
